---

- hosts: all

  tasks:

  - name: Download zabbix repo
        get_url:
            url: "https://repo.zabbix.com/zabbix/5.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_5.0-1+focal_all.deb"
            dest: /tmp/zabbix.deb

      - name: Install zabbix repo
        become: yes
        apt:
            deb: /tmp/zabbix.deb
            state: present

 - name: Install zabbix agent
        become: yes
        apt:
            name: zabbix-agent
            state: present
            update_cache: yes


- name: Stop service zabbix-agent
        become: yes
        service:
            name: zabbix-agent
            state: stopped

- name: Remove zabbix config file
        become: yes
        file:
            path: /etc/zabbix/zabbix_agentd.conf
            state: absent

- name: Create new zabbix config file from template
        become: yes
        template:
            src: "/etc/ansible/roles/zabbix/templates/zabbix_agentd.conf.j2"
            dest: "/etc/zabbix/zabbix_agentd.conf" 


    notify:

      - Start Zabbix-agent

  handlers:

  - name: zabbix-agent systemd

    systemd:
     name: zabbix-agent.service
     enabled: yes
     state: started
